version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/MkartLogistics.API"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "nuget"
    directory: "/src/MkartLogistics.Core"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "nuget"
    directory: "/src/MkartLogistics.Data"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
